package util;

import structures.MyHashMap;

public class DonationMetadata {

    public static final MyHashMap<String, String> TIPO_GOBIERNO = new MyHashMap<>();
    public static final MyHashMap<String, String> MES_MOVIMTO = new MyHashMap<>();
    public static final MyHashMap<String, String> TIPO_USO = new MyHashMap<>();
    public static final MyHashMap<String, String> TIPO_BIEN = new MyHashMap<>();
    public static final MyHashMap<String, String> HEADER_DESCRIPTIONS = new MyHashMap<>();

    static {
        // TIPO_GOBIERNO
        TIPO_GOBIERNO.put("E", "Gobierno Nacional");
        TIPO_GOBIERNO.put("R", "Gobierno Regional");

        // MES_MOVIMTO
        MES_MOVIMTO.put("01", "ENERO");
        MES_MOVIMTO.put("02", "FEBRERO");
        MES_MOVIMTO.put("03", "MARZO");
        MES_MOVIMTO.put("04", "ABRIL");
        MES_MOVIMTO.put("05", "MAYO");
        MES_MOVIMTO.put("06", "JUNIO");
        MES_MOVIMTO.put("07", "JULIO");
        MES_MOVIMTO.put("08", "AGOSTO");
        MES_MOVIMTO.put("09", "SETIEMBRE");
        MES_MOVIMTO.put("10", "OCTUBRE");
        MES_MOVIMTO.put("11", "NOVIEMBRE");
        MES_MOVIMTO.put("12", "DICIEMBRE");

        // TIPO_USO
        TIPO_USO.put("C", "CONSUMO");
        TIPO_USO.put("V", "VENTA");
        TIPO_USO.put("D", "DONACION");
        TIPO_USO.put("H", "RECURSOS HUMANOS");
        TIPO_USO.put("P", "PARA PRODUCCION");

        // TIPO_BIEN
        TIPO_BIEN.put("B", "BIEN");

        // Header Descriptions
        HEADER_DESCRIPTIONS.put("ANO_EJE", "AÑO DE CONSULTA");
        HEADER_DESCRIPTIONS.put("TIPO_GOBIERNO", "Código de Tipo de Gobierno");
        HEADER_DESCRIPTIONS.put("TIPO_GOBIERNO_NOMBRE", "Descripción de tipo de gobierno");
        HEADER_DESCRIPTIONS.put("SECTOR", "CODIGO DEL SECTOR");
        HEADER_DESCRIPTIONS.put("SECTOR_NOMBRE", "NOMBRE AL SECTOR QUE PERTENECE");
        HEADER_DESCRIPTIONS.put("PLIEGO", "CODIGO DE PLIEGO");
        HEADER_DESCRIPTIONS.put("PLIEGO_NOMBRE", "NOMBRE DEL PLIEGO AL QUE PERTENECE");
        HEADER_DESCRIPTIONS.put("SEC_EJEC", "CODIGO DE SECUENCIA DE EJECUTORA");
        HEADER_DESCRIPTIONS.put("EJECUTORA", "CODIGO DE EJECUTORA");
        HEADER_DESCRIPTIONS.put("EJECUTORA_NOMBRE", "DESCRIPCION DE SECUENCIA DE EJECUTORA");
        HEADER_DESCRIPTIONS.put("ALMACEN", "CODIGO DE ALMACEN");
        HEADER_DESCRIPTIONS.put("SEC_ALMACEN", "CODIGO DE SECUENCIA DE ALMACEN");
        HEADER_DESCRIPTIONS.put("NOMBRE_ALMACEN", "DESCRIPCION DE ALMACEN");
        HEADER_DESCRIPTIONS.put("TIPO_TRANSAC", "TIPO DE TRANSACCION");
        HEADER_DESCRIPTIONS.put("NOMBRE_TIPO_TRANSACCION", "DESCRIPCION DE TIPO DE TRANSACCION");
        HEADER_DESCRIPTIONS.put("NRO_MOVIMTO", "NUMERO DE MOVIMIENTO DE ENTRADA DE ALMACEN");
        HEADER_DESCRIPTIONS.put("NRO_ORDEN", "NUMERO DE ORDEN DE COMPRA");
        HEADER_DESCRIPTIONS.put("PROVEEDOR", "CODIGO DE PROVEEDOR");
        HEADER_DESCRIPTIONS.put("NOMBRE_PROVEEDOR", "NOMBRE DE PROVEEDOR");
        HEADER_DESCRIPTIONS.put("OBSERVACION", "DESCRIPCION DE OBSERVACION");
        HEADER_DESCRIPTIONS.put("FECHA_MOVIMTO", "FECHA DE MOVIMIENTO DE ENTRADA DE ALMACEN");
        HEADER_DESCRIPTIONS.put("MES_MOVIMTO", "CODIGO DE MES DE MOVIMIENTO DE NEA");
        HEADER_DESCRIPTIONS.put("NOMBRE_MES", "DESCRIPCION DE MES DE MOVIMIENTO DE NEA");
        HEADER_DESCRIPTIONS.put("TIPO_USO", "CODIGO DE TIPO DE USO");
        HEADER_DESCRIPTIONS.put("NRO_GUIA", "NUMERO DE GUIA DE REMISION DEL PROVEEDOR");
        HEADER_DESCRIPTIONS.put("NRO_FACTURA", "NUMERO DE DOCUMENTO DE PECOSA");
        HEADER_DESCRIPTIONS.put("ESTADO_KARDEX", "ESTADO DE KARDEX CUYO INDICADOR PUEDE SER N O S.");
        HEADER_DESCRIPTIONS.put("FECHA_REG", "FECHA DE REGISTRO");
        HEADER_DESCRIPTIONS.put("DOCUM_CONFIRMA", "DOCUMENTO DE CONFORMIDAD DE INGRESOS");
        HEADER_DESCRIPTIONS.put("FECHA_CONFIRMA", "FECHA DE CONFORMIDAD DE INGRESOS");
        HEADER_DESCRIPTIONS.put("GLOSA", "DESCRIPCION DE GLOSA DE INGRESO");
        HEADER_DESCRIPTIONS.put("TIPO_BIEN", "TIPO DE BIEN");
        HEADER_DESCRIPTIONS.put("GRUPO_BIEN", "CODIGO DE GRUPO DE BIEN");
        HEADER_DESCRIPTIONS.put("NOMBRE_GRUPO", "NOMBRE DEL GRUPO DEL BIEN A QUE PERTENECE");
        HEADER_DESCRIPTIONS.put("CLASE_BIEN", "CODIGO DE CLASE DE BIEN");
        HEADER_DESCRIPTIONS.put("NOMBRE_CLASE", "NOMBRE DE LA CLASE AL QUE PERTENECE");
        HEADER_DESCRIPTIONS.put("FAMILIA_BIEN", "CODIGO DE FAMILIA DE BIEN");
        HEADER_DESCRIPTIONS.put("NOMBRE_FAMILIA", "NOMBRE DE LA FAMILIA AL QUE PERTENECE");
        HEADER_DESCRIPTIONS.put("ITEM_BIEN", "CODIGO DE ITEM DE BIEN");
        HEADER_DESCRIPTIONS.put("NOMBRE_ITEM", "DESCRIPCION DE ITEM DE BIEN");
        HEADER_DESCRIPTIONS.put("UNIDAD_MEDIDA", "CODIGO DE UNIDAD DE MEDIDA DE CODIGO DE ITEM");
        HEADER_DESCRIPTIONS.put("NOMBRE_UMEDIDA", "DESCRIPCION DE CODIGO DE UNIDAD DE MEDIDA DE CODIGO DE ITEM");
        HEADER_DESCRIPTIONS.put("MARCA", "CODIGO DE MARCA");
        HEADER_DESCRIPTIONS.put("NOMBRE_MARCA", "NOMBRE DE MARCA");
        HEADER_DESCRIPTIONS.put("CANT_ARTICULO", "CANTIDAD DE ARTICULO");
        HEADER_DESCRIPTIONS.put("PRECIO_UNIT", "PRECIO UNITARIO DEL ITEM");
        HEADER_DESCRIPTIONS.put("VALOR_TOTAL", "VALOR TOTAL DEL ITEM");
    }
}
